apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      automountServiceAccountToken: false
      containers:
        - name: auth
          image: auth-app:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8081
              protocol: TCP
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
              ephemeral-storage: "500Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
              ephemeral-storage: "1Gi"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "eureka"
            - name: SPRING_CLOUD_COMPATIBILITY_VERIFIER_ENABLED
              value: "false"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
            - name: DATABASE_URL
              value: jdbc:postgresql://postgres:5432/auth_db
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: ITINERARY_MAIN_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: ITINERARY_MAIN_SECRET
            - name: PAYMENT_SERVICE_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: PAYMENT_SERVICE_SECRET
            - name: SPRING_ACTIVEMQ_BROKER_URL
              value: tcp://activemq:61616
            - name: SPRING_ACTIVEMQ_USER
              valueFrom:
                secretKeyRef:
                  name: activemq-secret
                  key: username
            - name: SPRING_ACTIVEMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: activemq-secret
                  key: password
            - name: SPRING_JMS_PUB_SUB_DOMAIN
              value: "false"
            - name: SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE_BASE_URL
              value: http://auth:8080
            - name: SPRING_BOOT_ADMIN_CLIENT_INSTANCE_MANAGEMENT_BASE_URL
              value: http://auth:8081
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "health,info,prometheus"
            - name: MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED
              value: "true"
          envFrom:
            - configMapRef:
                name: common-actuator-config
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 10
      restartPolicy: Always
