apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
data:
  ITINERARY_MAIN_SECRET: Y2FkOTVmOTYyZmI3ZGM0NDg5MDZiYjY3OTg4MzRiMmUwN2NjMGUxMzU5MWI0NmUyNTRiZThlZDY0MTQ4NDVkYg==
  PAYMENT_SERVICE_SECRET: YmVjZTVhNzc0ZmJlMTA3M2RlNDc0MDViNWRkZjc4Mzc4NjgyMmZmYTExMjljMmQyMTdhMThlZjJlZjY1NmU5Ng==


