apiVersion: v1
kind: ConfigMap
metadata:
  name: common-actuator-config
data:
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "*"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"
  MANAGEMENT_ENDPOINTS_WEB_BASE_PATH: "/actuator"
  MANAGEMENT_SERVER_PORT: "8081"
