apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  labels:
    app: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      automountServiceAccountToken: false
      containers:
        - name: eureka-server
          image: eureka-server:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761
              protocol: TCP
              name: eureka
            - containerPort: 8762
              protocol: TCP
              name: management
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
              ephemeral-storage: "500Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
              ephemeral-storage: "1Gi"
          env:
            - name: EUREKA_INSTANCE_HOSTNAME
              value: eureka-server
            - name: SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE_BASE_URL
              value: http://eureka-server:8761
            - name: SPRING_BOOT_ADMIN_CLIENT_INSTANCE_MANAGEMENT_BASE_URL
              value: http://eureka-server:8762
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "health,info,prometheus,eureka"
            - name: MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED
              value: "true"
          envFrom:
            - configMapRef:
                name: common-actuator-config
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 5

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 40
            periodSeconds: 10
            failureThreshold: 5
      restartPolicy: Always

