apiVersion: apps/v1
kind: Deployment
metadata:
  name: itinerary-main
  labels:
    app: itinerary_main
spec:
  replicas: 2
  selector:
    matchLabels:
      app: itinerary-main
  template:
    metadata:
      name: itinerary-main
      labels:
        app: itinerary-main
    spec:
      containers:
        - name: itinerary-main
          image: itinerary-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/itinerary
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: ITINERARY_MAIN_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: ITINERARY_MAIN_SECRET
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
            - name: SPRING_ACTIVEMQ_BROKER_URL
              value: tcp://activemq:61616
            - name: SPRING_ACTIVEMQ_USER
              valueFrom:
                secretKeyRef:
                  name: activemq-secret
                  key: username
            - name: SPRING_ACTIVEMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: activemq-secret
                  key: password
          envFrom:
            - configMapRef:
                name: common-actuator-config
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 10
      restartPolicy: Always
      