apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  labels:
    app: payments
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      name: payments
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: payments-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/itinerary
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: PAYMENT_SERVICE_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: PAYMENT_SERVICE_SECRET
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: org.postgresql.Driver      
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: SPRING_ACTIVEMQ_BROKER_URL
              value: tcp://activemq:61616
            - name: SPRING_ACTIVEMQ_USER
              valueFrom:
                secretKeyRef:
                  name: activemq-secret
                  key: username
            - name: SPRING_ACTIVEMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: activemq-secret
                  key: password
          envFrom:
            - configMapRef:
                name: common-actuator-config
      restartPolicy: Always


      