apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s

    scrape_configs:
      - job_name: 'spring-boot-services'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets:
            - 'auth:8081'
            - 'payments:8081'
            - 'itinerary-main:8081'
            - 'gateway:8081'
            - 'eureka-server:8081'
            - 'admin-server:8081'
            labels:
              environment: 'kubernetes'